### ISSUE TITLE
Repo name

### ISSUE THREAD

**Issue by maedoc** [anywave/aw-sdk#1]
When developers fork the SDK, it will be named "sdk" in their list of repos.

It would be good practice to rename to "aw-sdk" or "anywave-sdk" so that the repo is always distinguished from other SDKs that may exist.

I can do this if you agree.

**Comment by bcolombet** [comment]
Le 12/03/2015 11:52, maedoc a écrit :
>
> When developers fork the SDK, it will be named "sdk" in their list of 
> repos.
>
> It would be good practice to rename to "aw-sdk" or "anywave-sdk" so 
> that the repo is always distinguished from other SDKs that may exist.
>
> I can do this if you agree.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/anywave/sdk/issues/1>.
>
Oui, d'accord. Bonne remarque.

-- 
Bruno Colombet
INSERM U1106 Institut de Neurosciences des Systèmes
Centre MEG, Service de Neurophysiologie Clinique
CHU Timone - Rue Saint Pierre-13385 Marseille Cedex 5
04 91 38 55 40
+33 4 91 38 55 40
http://ins.univ-amu.fr
http://meg.univ-amu.fr/wiki/AnyWave
